### ISSUE TITLE
Can Llama-gpt be installed w/out Docker?

### ISSUE THREAD

**Issue by bmullan** [getumbrel/llama-gpt#14]
I use Ubuntu 22.04.3 LTS and also LXD "system" containers and try to avoid using Docker when I can because it
is duplicating in an application container (docker) what I'd rather install into an LXD container (fedora, debian, ubuntu, suse, alpine etc)

Docker runs fine when I have to use it and it also runs ok "nested" in an LXD container but Is there a way to install without docker?

thanks for any info
brian

**Comment by fabricionaweb** [comment]
I do belive you can do it, but will require search and effort from your side, maybe a lot

The compose is the junction of this two images

https://github.com/getumbrel/llama-gpt/blob/master/ui/Dockerfile
https://github.com/getumbrel/llama-gpt/blob/master/api/Dockerfile

Which is basicaly npm and python running together... you may want create some daemon by yourself...

**Comment by mayankchhabra** [comment]
As @fabricionaweb pointed out, you may be able to get it working by running Chabot UI and llama-cpp-python directly on your host system. But this isn't aligned with our project, since the idea with Dockerization is to not add dependencies and such on the host, keep the host system clean, and offer a one-line deployment method on a a variety of hardware. I'll go ahead and close this issue for now, but happy to revisit if there's more support for non-Docker, host-based installations.
