### ISSUE TITLE
Can you please add more details on OPENAI_API_KEY env var in Readme

### ISSUE THREAD

**Issue by AI-Zebra** [getumbrel/llama-gpt#33]
The UI has OPENAI_API_KEY set to sk-xxxxxxxxxxxxx.
Please can you explain in readme, what is its purpose? How can we generate new API keys for different teams using this deployment?

**Comment by nmfretz** [comment]
Hi @AI-Zebra, thanks for the suggestion to clarify the `OPEN_API_KEY` environment variable in the readme.

The `OPEN_API_KEY` environment variable for the `llama-gpt-ui` container originates from Mckay Wrigley's [Chatbot UI](https://github.com/mckaywrigley/chatbot-ui) (which our UI is forked from). In Chatbot UI, its purpose is to authenticate and interact with OpenAI's chat models, because Chatbot UI is an alternative user interface to ChatGPT.

For LlamaGPT, we have set `OPEN_API_KEY` to a dummy string because we've modified the UI to showcase only self-hosted models, rendering the need for a valid OpenAI API key unnecessary. We included the key in its dummy form to retain compatibility with the original Chatbot UI setup.

Definitely check out [Chatbot UI](https://github.com/mckaywrigley/chatbot-ui) if you are looking for a user interface for OpenAI chat models. You can generate API keys from https://platform.openai.com/account/api-keys

**Comment by AI-Zebra** [comment]
Thanks a lot @nmfretz for the quick answer..
